# site-wide settings
title: A fynnomenal blog
author:
  name: fynnomenon
  email: fynn753@gmail.com
description: >- 
  A fynnomenal blog about AI stuff, I guess?

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima-specific settings (applicable to Minima v3 and above only)
minima:
  skin: auto
  social_links:
    - title: fynnomenon on discord
      icon: discord
      url: "https://discordapp.com/users/504720288752205827"
    - title: fynnomenon on X
      icon: x-twitter
      url: "https://x.com/fynn_61"
  hide_site_feed_link: true
